### ISSUE TITLE
the metrics

### ISSUE THREAD

**Issue by zyfsa** [PKU-ICST-MIPL/CMCP#1]
您好，请问一下在您代码CMCP函数的几个返回值，表示什么意思啊
[mapIA, mapIT, mapTA, mapTI]
麻烦您解释一下，谢谢

**Comment by PKU-ICST-MIPL** [comment]
你好！
这4个返回参数都是mapXY的形式，指的是以X为查询，Y为检索库，得到的MAP值。具体地：
mapIA：以图像检索图像和文本的MAP指
mapIT：以图像检索文本的MAP值
mapTA：以文本检索图像和文本的MAP值
mapTI：以文本检索图像的MAP值
